def register(rt):
    rt.register(
        "stt://local/session/{session}/command/start",
        "python://uristt.handlers:session_start",
        kind="command",
        operation="stt.session.start",
        approval="required",
        side_effects=True,
    )
    rt.register(
        "stt://local/session/{session}/query/transcript",
        "python://uristt.handlers:session_transcript",
        kind="query",
        operation="stt.session.transcript",
    )
    rt.register(
        "stt://local/audio/command/transcribe",
        "python://uristt.handlers:audio_transcribe",
        kind="command",
        operation="stt.audio.transcribe",
        approval="required",
        side_effects=True,
    )
